# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51681e75846e7c2b928bd362744af7c9701a48ca44790ed929c94a69556615ae7770ef1036b781de3e86e0141714bdc0363dcb9e5b9d529f65ea6e2126c1be75

test:
  secret_key_base: c3fa3236d43f4940a98596daabc41d2099c0d44b26565222f661255f1a9cb077b6de78fc0c4cd8893b27cdfc316b732624220f4c2d9bfa6e0a8eae36eca802e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
